include:
  # CAMBIO AQUÍ: Usar el shield peripheral para la izquierda
  - board: nice_nano_v2
    shield: corne_left_peripheral
    artifact-name: corne_left

  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right

  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    artifact-name: corne_dongle

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: ble_reset
